---
- name:
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    suser: fedora
    spasswd: redhat

  tasks:
    - name: 
      copy:
        content: "username={{ suser }}\npassword={{ spasswd }}\n"
        dest: files/creds.txt
