---
- name:
  hosts: localhost
  connection: local
  gather_facts: true
  
  tasks:
  - name: Printing hostname thru facts
    debug:
      msg: "{{ ansible_facts['hostname'] }}"

  - name: Printer hostname thru inventory
    debug:
      msg: "{{ inventory_hostname }}"
