---
- name:
  hosts: localhost
  connection: local
  gather_facts: false
  
  tasks:
  - name:
    stat:
      path: ./test-file.txt
    register: test_file

  - name: Output
    debug:
      msg: "File does exist."
    when: test_file.stat.exists == true
